export const TEMPLATES = {
  'traditional-royal': {
    id: 'traditional-royal',
    name: 'Traditional Royal',
    description: 'Maroon + antique gold with grand mandalas and ornate Indian filigree borders.',
    bg: 'bg-gradient-to-b from-[#2D060E] via-[#3D0813] to-[#1A0307]',
    cardBg: 'bg-gradient-to-b from-[#4A0A17] to-[#2B050E]',
    borderColor: 'border-gold-500/40',
    accentText: 'text-gold-gradient',
    subText: 'text-gold-200/80',
    primaryColor: '#580D1A',
    accentColor: '#D4AF37',
    badge: '👑 Royal Heritage',
  },
  'south-indian-temple': {
    id: 'south-indian-temple',
    name: 'South Indian Temple',
    description: 'Temple-inspired red & turmeric gold with brass vilakku lamps, lotus, and auspicious banana leaf accents.',
    bg: 'bg-gradient-to-b from-[#350B0B] via-[#4A0E17] to-[#1E050A]',
    cardBg: 'bg-gradient-to-b from-[#52131D] to-[#2D0910]',
    borderColor: 'border-yellow-600/50',
    accentText: 'text-yellow-400',
    subText: 'text-amber-200/90',
    primaryColor: '#7B1113',
    accentColor: '#E5A93C',
    badge: '🪔 Temple Sacred',
  },
  'marigold-celebration': {
    id: 'marigold-celebration',
    name: 'Marigold Celebration',
    description: 'Warm ivory background with vibrant haldi yellow and marigold orange garlands.',
    bg: 'bg-gradient-to-b from-[#1C1008] via-[#2D1808] to-[#140A04]',
    cardBg: 'bg-gradient-to-b from-[#3D200B] to-[#241306]',
    borderColor: 'border-amber-500/40',
    accentText: 'text-amber-400',
    subText: 'text-amber-100/90',
    primaryColor: '#F37021',
    accentColor: '#FFC72C',
    badge: '🌼 Haldi & Marigold',
  },
  'royal-rajasthani': {
    id: 'royal-rajasthani',
    name: 'Royal Rajasthani',
    description: 'Deep crimson ruby red with gold jharokha arches, royal peacocks, and haveli patterns.',
    bg: 'bg-gradient-to-b from-[#2E0514] via-[#400B1E] to-[#18020A]',
    cardBg: 'bg-gradient-to-b from-[#540E28] to-[#2E0716]',
    borderColor: 'border-gold-400/50',
    accentText: 'text-gold-gradient',
    subText: 'text-rose-200/80',
    primaryColor: '#800020',
    accentColor: '#E6C665',
    badge: '🏰 Royal Haveli',
  },
  'elegant-floral': {
    id: 'elegant-floral',
    name: 'Elegant Floral',
    description: 'Ivory and delicate blush rose with refined gold foil accents and timeless minimal floral filigree.',
    bg: 'bg-gradient-to-b from-[#1F1719] via-[#2A1D20] to-[#140E10]',
    cardBg: 'bg-gradient-to-b from-[#38262B] to-[#201518]',
    borderColor: 'border-rose-400/40',
    accentText: 'text-rose-300',
    subText: 'text-stone-300',
    primaryColor: '#C88A8A',
    accentColor: '#D4AF37',
    badge: '🌸 Pastel Elegance',
  },
  'minimal-traditional': {
    id: 'minimal-traditional',
    name: 'Minimal Traditional',
    description: 'Warm cream aesthetic with understated hairline gold borders and subtle sacred motifs.',
    bg: 'bg-gradient-to-b from-[#1A1817] via-[#262322] to-[#121110]',
    cardBg: 'bg-gradient-to-b from-[#332F2D] to-[#1C1A19]',
    borderColor: 'border-stone-600/40',
    accentText: 'text-gold-300',
    subText: 'text-stone-300',
    primaryColor: '#4A4238',
    accentColor: '#D4AF37',
    badge: '✨ Minimal Auspicious',
  },
};
